### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by novos7** [winyl-player/winyl#11]
I have a problem installing of the Winyl. The same has also happened with the previous version.
![ice_screenshot_20180331-054702](https://user-images.githubusercontent.com/30302436/38159531-9a065fe6-34aa-11e8-900d-f88e2d65c5e8.png)

**Comment by alexkx** [comment]
What folder are you trying to install to?

**Comment by novos7** [comment]
I think the default. I was not asked to choose a folder during installation. I downloaded the archive with the program and unpacked it on the desktop.

**Comment by alexkx** [comment]
You can try to uninstall the program (without deleting settings and the library) and install it again.
