### ISSUE TITLE
Covers bug

### ISSUE THREAD

**Issue by novos7** [winyl-player/winyl#12]
There is bug in the program related to the covers. After adding a song or album to the program without a defined cover, Winyl uses a cover from others my albums instead blank cover. One likes the most ;)
![ice_screenshot_20180331-055936](https://user-images.githubusercontent.com/30302436/38159523-6a874cda-34aa-11e8-86ff-db9f165ebde1.png)
![ice_screenshot_20180331-060006](https://user-images.githubusercontent.com/30302436/38159524-6c5436ae-34aa-11e8-9c72-16a05922fac2.png)
![ice_screenshot_20180331-060710](https://user-images.githubusercontent.com/30302436/38159525-6deb38d2-34aa-11e8-9f1a-bf9bb23e18e1.png)
![ice_screenshot_20180331-061519](https://user-images.githubusercontent.com/30302436/38159549-f4c70070-34aa-11e8-9272-73287d14808c.png)

**Comment by alexkx** [comment]
If you have any image file in the folder it will be used as the cover art. If you don't want this then remove the file.

**Comment by novos7** [comment]
Thanks for the answer. You're right!
