### ISSUE TITLE
how to edit or remove some elements of playlist

### ISSUE THREAD

**Issue by vasiokivanov** [winyl-player/winyl#17]
how to edit or remove some elements of playlist. for example - how to remove rating stars ? they are annoying.

**Comment by novos7** [comment]
It can't be done through the program. You need to edit the skin.

**Comment by vasiokivanov** [comment]
how to do that ?

**Comment by alexkx** [comment]
I'm afraid there isn't any manual. You need to unpack a skin and remove Rating section from Playlist.xml file.
