### ISSUE TITLE
Incompatible with the latest last.fm scrobble client

### ISSUE THREAD

**Issue by zag2me** [winyl-player/winyl#22]
As title, the software seems to work great with the last.fm legacy scrobbler, but not with the newest client. I spent a good while going round in circles trying to make it work until I realized the setting would not stick because it didnt work with the latest version.

Installing the legacy last.fm client and the setting finally stuck when I hit the last.fm checkbox in the winyl settings.

**Comment by alexkx** [comment]
Yes the old API is incompatible with the new scrobbler. And it seems there is not any API for the new scrobbler, so last.fm part should be rewritten from scratch without using client API and using scrobbling API instead. Considering there is not C++ library for the scrobbling API it can be too much work.
You can still use legacy client it should work fine.

**Comment by zag2me** [comment]
Great thx for the explanation. Maybe just changing the wording of the setting in Winyl would be enough. Just to mention it only works with classic scrobbler.

**Comment by alexkx** [comment]
> Maybe just changing the wording of the setting in Winyl would be enough.

I've changed it the latest version.

Closing the issue for now. It cannot be fixed to work with the new Last.fm client due to the lack of API.
