### ISSUE TITLE
Stars Rating Fail

### ISSUE THREAD

**Issue by ancich** [winyl-player/winyl#30]
I would switch to this player in a second except for one major bug.  The 100s of MP3 files I have are all rated from 1 to 5 stars.   When I open those MP3s in Winyl, they all default to being unrated.  There is NO way I am going to re-rate 100s of MP3s.  Is it that hard for you to read the star rating from the MP3 file????

**Comment by roman6626** [comment]
In principle, stars are not needed at all. They can be removed from the skin.

**Comment by blackcrack** [comment]
rating belongs not skins.. rating is in a db from the player and is not directly player releated and comes from a long term using this player.. if you use an other player for your musik @ancich must you build up again in any way the rating of your music parts .. so, what you complain as a issue ?! This is User related and cant take with or converting in an other music-player !

please close this issue. left at the comment-button @ancich

**Comment by ancich** [comment]
5 star rating is one of the properties of most MP3 files.  WHAT is the issue of updating that field in the MP3 file itself, so it stays with the file much like a album thumbnail does.    

I WON'T CLOSE this issue.

**Comment by ancich** [comment]
Oh, and thanks for taking over a FULL year to get back to me, you wankers.

**Comment by ancich** [comment]
Closing issue because I have moved onto the Dopemine player which is superior.
