### ISSUE TITLE
This is the end?

### ISSUE THREAD

**Issue by roman6626** [winyl-player/winyl#36]
Will Winyl no longer be developed and maintained by the author? He died?
Can we wait for further development?

**Comment by zag2me** [comment]
Seems development slowed down and nothing new. I personally went back to the open-source version of Winamp (called WACUP) that is now in active development again.

https://getwacup.com/

![ddbr1i4-90162195-da7d-47e7-a19d-67f8af751562](https://user-images.githubusercontent.com/1050512/69136622-166eb800-0ab3-11ea-9876-90471ac52f2f.png)

**Comment by Mlinotest** [comment]
I hope not! I just came back from foobar2000. Looks like I'm staying with Winyl, haha

**Comment by blackcrack** [comment]
this be 2 different programs, use it or use it not..

**Comment by alexkx** [comment]
I just don't have time to work on the project right now, sorry. But the program is in the perfect working state there aren't any critical issues, so you can use it without any problems if the lack of updates is not an issue for you.
