### ISSUE TITLE
Ability to disable fade in/out on playback and seek

### ISSUE THREAD

**Issue by Degru** [winyl-player/winyl#37]
Maybe I'm not seeing this option, but this is my main gripe with this player. If i click on a track with a sharp impact at the start,  for example, this gets totally swallowed by the fade in and is quite unsatisfying. Same when skipping around a track. It ruins the beginnings of quite a few songs and is a black mark on what is otherwise an excellent player.

**Comment by roman6626** [comment]
Right. You will not see. The author stopped working on the project in 2018. Stopped even answering forum questions. The project is dead.

**Comment by alexkx** [comment]
The start and the end of a song never fades in/fades out.
Anyway if you want to disable it completely edit Settings.xml file that is located in %appdata%\Winyl

Find line:
`<Device ID="-1" Driver="0" Bit32="1" SoftMix="0" />`
Then edit it like this:
`<Device ID="-1" Driver="0" Bit32="1" SoftMix="0" NoEffect="1" />`

Note that it only works in WASAPI/ASIO modes for now.
