### ISSUE TITLE
Playlist improvements

### ISSUE THREAD

**Issue by AFaustini** [winyl-player/winyl#4]
The playlist information is very sparse.
It will be nice if we can put some more information. Even in the Album line, like this:
![image](https://user-images.githubusercontent.com/32999190/36934799-a1750158-1ecd-11e8-817e-fbd85be31912.png)
I can only achieve this by editing the skin.

**Comment by alexkx** [comment]
Do you mean add option somewhere in the settings dialog?
Editing the skin is the right way to do it actually, the main purpose of the skinnable UI that users can customize the UI whatever they like.

**Comment by AFaustini** [comment]
Understood. I discover Winyl yesterday, and i love it. My suggestion is for add a option, but now i understand why it works like this.

**Comment by alexkx** [comment]
Yes, it works this way.
I'm closing the issue for now, it is already possible by editing the skin and will be hard to implement the other way with the current architecture. It's like one of the hardest part of the player should be rewritten.
