### ISSUE TITLE
CoverArt Stuck 

### ISSUE THREAD

**Issue by FaySmash** [winyl-player/winyl#7]
**Expectation**: I have a folder with a lot of songs, all with different CoverArts. When I open up this folder with Winyl and play a song, the CoverArt image display changes to the one of the currently playing song. If I choose another song, the CoverArt image display should change again, to match the CoverArt of the now currently playing song.

**Reality**: The CoverArt is stuck with the image of the first played song.

**Steps to reproduce**: Put two songs with different CoverArts in a folder, navigate into it with winyl, start a song, then the other and look if the CoverArt changes.

Sample Video of the Bug:
https://youtu.be/wwNvl6McSaQ

**Comment by FaySmash** [comment]
@hairycactus okay, I'll try with the skin disabled! Hopefully it would be possible to invert a fix/workaround for my issue even with this skin applied..?
On the counter part for testing, here is the skin I use: https://pep0.deviantart.com/art/Material-Light-and-Dark-for-Winyl-8-colors-597613989

**Comment by alexkx** [comment]
I think it's because the cover art is a part of album right now, so it only changes when the album name or the folder of the track changed.

Are these files part of one album? If yes is there a reason why they have different cover arts?

**Comment by FaySmash** [comment]
@hairycactus it's independent of the theme

@alexkx then it would have to be changed to be a part of the song. Those files are part of the same folder but none of them has an album defined in the ID3-tag. And ofc there's a reason, all those songs and many, **many** more are downloaded from youtube playlists, the CoverArts are the youtube thumbnails. I also spend quite a time to assign songs of such compilations CoverArts when they didn't fit/didn't have one, so it's pretty annoying to me to not see the correct one for each song.

**Comment by alexkx** [comment]
Yes, I guess it's time to change the behaviour for embedded cover art, there was already similar requests in the past. External cover art should not be affected by this, it's always part of the album.

**Comment by alexkx** [comment]
Changed. There is still a possibility to cover art stuck when an user has tracks with embedded cover arts + tracks without embedded cover arts + random jpeg/png files in one folder.
But to fix this the optimization for huge external cover arts should be completely removed. I don't want to do that and I don't believe any user have such a mess in one folder.

**Comment by FaySmash** [comment]
really nice, thanks for the fast implementation!

**Comment by FaySmash** [comment]
@alexkx I downloaded the current repo and compiled it myself, but I still have this problem. Shouldn't the ZIP download of the whole repo already include the CoverArt fix? Because it's listed in the CHANGES.md "- Changed behaviour when reloading cover arts."

**Comment by alexkx** [comment]
It does include the fix. Do you have any image files in the folder with your music files?

**Comment by FaySmash** [comment]
@alexkx no I haven't (as you mentioned, it would cause this bug). To make further trouble shooting easier, I'm sharing a folder with you whith songs which are affected by this bug:https://homedrive.zapto.org/nextcloud/index.php/s/C5GddG63KC2ZEDa (it's the same folder as shown in the example video in the OP)

**Comment by alexkx** [comment]
I downloaded the first 3 files and can't reproduce the issue. Are you sure you compiled the latest master branch?

Here I compiled the master to try:
[Winyl.zip](https://github.com/winyl-player/winyl/files/1837362/Winyl.zip)

Let me know if it still doesn't work.

**Comment by FaySmash** [comment]
@alexkx thank you for the application! Tbh it seems it was my fault, I was looking at the Album Cover Art, not Song Cover Art (after compiling I tested it out with the default Winyl design but because I'm usually using a different one I looked at the wrong Image).
So you can leave this issue closed by good, I'm looking forward to the official 3.4 release! :D 
Thank you for your hard work and I'm really sorry I reported a non-existent issue 😥

Where I was looking:
![unbenannt](https://user-images.githubusercontent.com/30392780/37795737-9e770b66-2e15-11e8-8e6a-fd713f4cc4d1.jpg)

Where I should have looked:
![unbenannt1](https://user-images.githubusercontent.com/30392780/37795741-a010e802-2e15-11e8-80fc-76cf7761bc1c.jpg)

**Comment by alexkx** [comment]
Good to know that it works fine. By the way, you can set different album names for these files if you want to ungroup them to display different cover arts in the list.

**Comment by FaySmash** [comment]
@alexkx yes but I don't wanna spam my artists section :p
